dockerfiles/centos/centos-7/centos-7-base/Dockerfile, dockerfiles/debian/debian-8/debian-8-base/Dockerfile, dockerfiles/fedora/fedora-22/fedora-22-base/Dockerfile, dockerfiles/fedora/fedora-23/fedora-23-base/Dockerfile, dockerfiles/fedora/fedora-24/fedora-24-base/Dockerfile, dockerfiles/opensuse/opensuse-13.2/opensuse-13.2-base/Dockerfile, dockerfiles/opensuse/opensuse-42.1/opensuse-42.1-base/Dockerfile, dockerfiles/ubuntu/ubuntu-16.04/ubuntu-16.04-base/Dockerfile, dockerfiles/ubuntu/ubuntu-16.10/ubuntu-16.10-base/Dockerfile
Add the sudo package to the containers that did not have it installed.
This is needed by the hoop jumping usersetup.py does.
Signed-off-by: brian avery <brian.avery@intel.com>
=> dockerfiles: Add sudo to containers that need it

dockerfiles/opensuse/opensuse-13.2/opensuse-13.2-base/Dockerfile, dockerfiles/opensuse/opensuse-42.1/opensuse-42.1-base/Dockerfile, dockerfiles/opensuse/opensuse-42.2/opensuse-42.2-base/Dockerfile, dockerfiles/ubuntu/ubuntu-16.04/ubuntu-16.04-base/Dockerfile, dockerfiles/ubuntu/ubuntu-16.10/ubuntu-16.10-base/Dockerfile
bitbake now checks to see if we have a certain set of host tools
available for before it will launch a build. This check caught several
missing tools that are mostly used for testimage.  This commit adds
the missing tools.
What was missing:
opensuse-<all>  - hostname , ip
ubuntu-16-<all> - ping
Signed-off-by: brian avery <brian.avery@intel.com>
=> dockerfiles: add missing host tools to base

build_container.sh, dockerfiles/ubuntu/ubuntu-17.04/ubuntu-17.04-base/Dockerfile, dockerfiles/ubuntu/ubuntu-17.04/ubuntu-17.04-builder/Dockerfile
I wanted to do some testing of the upcoming YP release with the impending Ubuntu 17.04 release and thought a container made perfect sense.
At the same time I had to figure out how to build docker images when I'm behind a proxy (https://github.com/crops/yocto-dockerfiles/issues/16). This small PR contains two patches, one to enable build_container.sh to better function when behind a proxy and another to add an Ubuntu 17.04 image.
The first patch is, IMHO, immediately useful whilst the second may want to wait until Ubuntu 17.04 is released?
=> Add Zesty Zapus image and fix building behind a proxy

tests/container/smoke.sh
Some of the smoke tests put files in the $workdir which is set to
/tmp/tmp.GUID_smoke. This workdir is mounted from the host into the
container. If the tests are successful, this directory's contents are
removed. Previously, these tests were running as the default user 1000
in the container so if you were uid=1010 on the system, the smoke tests
would drop files in /tmp/tmp.GUID_smoke owned by uid=1000 and the final
smoke test cleanup to remove all the files from the /tmp/tmp.GUID_smoke
would fail.  Similarly, it's better to run as the user uid in case they
want to edit/modify/whatever the files.
Signed-off-by: brian avery <brian.avery@intel.com>
=> smoke.sh: run smoke tests container as user uid

dockerfiles/centos/centos-7/centos-7-base/Dockerfile, dockerfiles/centos/centos-7/centos-7-base/vncserver.patch
Patch /usr/bin/vncserver to no longer run "vncserver -kill $DISPLAY".
The vnc smoke test was failing for Centos 7. For some reason the default
xstartup file created by /usr/bin/vncserver would run "vncserver -kill
$DISPAY".
This command is not in the upstream tigervnc and it was having the
effect of killing the vncserver right after it was started.
Signed-off-by: Randy Witt <randy.e.witt@intel.com>
=> centos-7: Fix vnc test failure

dockerfiles/ubuntu/ubuntu-14.04/ubuntu-14.04-base/Dockerfile
realpath was added to HOSTTOOLS, so it is now needed in the image.
Signed-off-by: Randy Witt <randy.e.witt@intel.com>
=> ubuntu-14.04: Add realpath

build-install-dumb-init.sh, dockerfiles/centos/centos-7/centos-7-base/Dockerfile
Use python36 instead of python34.
This fixes the failures that were occurring due to "pip3" not being
found.
Signed-off-by: Randy Witt <randy.e.witt@intel.com>
=> Fix dumb-init tests on CentOS 7

tests/unit/test_runbitbake.py
In python3 stdout for Popen() is a byte stream, so it must be decoded to
strings. This change is necessary because travis switched to python3.
Signed-off-by: Randy Witt <randy.e.witt@intel.com>
=> test_runbitbake.py: Update to work with python3

.travis.yml, build_container.sh, distro-entry.sh, dockerfiles/centos/centos-7/centos-7-base/Dockerfile, dockerfiles/debian/debian-10/debian-10-base/Dockerfile, dockerfiles/debian/debian-9/debian-9-base/Dockerfile, dockerfiles/ubuntu/ubuntu-16.04/ubuntu-16.04-base/Dockerfile, dockerfiles/ubuntu/ubuntu-18.04/ubuntu-18.04-base/Dockerfile, dockerfiles/ubuntu/ubuntu-20.04/ubuntu-20.04-base/Dockerfile, install-buildtools.sh, tests/unit/test_runbitbake.py
* Improve the Debian & Ubuntu container configs to resolve issues seen with my use cases.
* Add a Dockerfile for Ubuntu 20.04
* Updated to buildtools-extended tarball from Yocto 3.1 for Centos 7 & Ubuntu 16.04.
=> Improve Ubuntu/Debian container configs, add Ubuntu 20.04 and update buildtools

.travis.yml, dockerfiles/centos/centos-8/centos-8-base/Dockerfile, dockerfiles/opensuse/opensuse-15.2/opensuse-15.2-base/Dockerfile
Add centos-8 and opensuse-15.2
while we are at it, sort the packages in alphabetical order to make it easier to catch what is present/missing.
=> timo/distro updates 7 2020: Add centos-8 and opensuse-15.2

dockerfiles/ubuntu/ubuntu-20.04/ubuntu-20.04-base/Dockerfile
A number of packages listed as "[Essentials](https://www.yoctoproject.org/docs/latest/ref-manual/ref-manual.html#ubuntu-packages)" in the Yocto Reference Manual are not in the Ubuntu image.
With this change, all the essential packages are installed in the image.
=> ubuntu: 20.04: Sync dependencies with Yocto Ref. Man.

.github/workflows/build-test-deploy.yml
Our old TravisCI workflow updated the upstream distro packages
once a week. Re-enable that behavior..
Reference:
https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events
Signed-off-by: Tim Orling <timothy.t.orling@intel.com>
=> github/workflows: build every Saturday at 00:52 UTC

deploy.sh
Since 'github/workflows: build every Saturday at 00:52 UTC' builds were
properly being scheduled, but not deployed.
=> deploy.sh: Deploy when event is 'schedule'

.github/workflows/build-test-deploy.yml, build-install-dumb-init.sh, dockerfiles/alma/alma-8/alma-8-base/Dockerfile, tests/container/vnc-in-container-test.sh
centos-8 can no longer fetch package repos, so drop it in favor of
almalinux.
centos-streams-8 has proven to be unstable on the Yocto Project
AutoBuilder so we will skip it. Not worth the headaches.
=> Drop centos-8 and replace with alma-8

build-install-dumb-init.sh
Automatic package discovery in newer setuptools fails with the following
error:
"""
GLOB sdist-make: /tmp/tmp.BST5jRIOuQ/dumb-init-1.2.5/setup.py
ERROR: invocation failed (exit code 1), logfile: /tmp/tmp.BST5jRIOuQ/dumb-init-1.2.5/.tox/log/GLOB-0.log
================================== log start ===================================
error: Multiple top-level packages discovered in a flat-layout: ['debian', 'testing'].
To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.
If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:
1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. …
=> build-install-dumb-init.sh: pin setuptools==59.6.0

build_container.sh, distro-entry.sh, dockerfiles/alma/alma-8/alma-8-base/Dockerfile, dockerfiles/debian/debian-10/debian-10-base/Dockerfile, dockerfiles/opensuse/opensuse-15.2/opensuse-15.2-base/Dockerfile, install-buildtools-make.sh
For alma-8, debian-10 and opensuse-15.2, with the 'kirkstone' Yocto
Project 4.0 release a new sanity check for make 4.1.2 is throwing an
error causing the containers to fail to build.
=> install-buildtools-make: fix make 4.1.2 sanity check

dockerfiles/alma/alma-8/alma-8-base/Dockerfile
Add procps for the 'ps' command for the dumb-init tests in the
poky-container.
Update the package list to be (mostly) in sync with:
http://docs.yoctoproject.org/ref-manual/system-requirements.html#centos-8-packages
Be consistent about spaces vs tabs.
=> alma-8: add procps; sync with docs

.github/workflows/build-test-deploy.yml, dockerfiles/fedora/fedora-36/fedora-36-base/Dockerfile
Fedora 36 was released on May 10, 2022
https://fedoraproject.org/wiki/Releases/36/ChangeSet
https://docs.fedoraproject.org/en-US/fedora/latest/
https://fedoramagazine.org/announcing-fedora-36/
=> Fedora: add fedora-36

.github/workflows/build-test-deploy.yml, dockerfiles/alma/alma-9/alma-9-base/Dockerfile
AlmaLinux 9 has been released for a while now
https://almalinux.org/blog/almalinux-9-now-available/ https://wiki.almalinux.org/release-notes/9.0.html
powertools is now known as crb
https://almalinux.discourse.group/t/powertools-on-almalinux-9/1296
=> Alma: add alma-9

distro-entry.sh, dockerfiles/alma/alma-8/alma-8-base/Dockerfile, dockerfiles/debian/debian-10/debian-10-base/Dockerfile, dockerfiles/opensuse/opensuse-15.2/opensuse-15.2-base/Dockerfile, dockerfiles/opensuse/opensuse-15.3/opensuse-15.3-base/Dockerfile, dockerfiles/opensuse/opensuse-15.4/opensuse-15.4-base/Dockerfile, dockerfiles/ubuntu/ubuntu-18.04/ubuntu-18.04-base/Dockerfile, install-buildtools-make.sh, install-buildtools.sh
This patchset fixes the CI build breakage seen with the addition of the python 3.8 dependency and the missing make-nativesdk-standalone binaries we were pulling from the autobuilder. It also upgrades to installed buildtools to the most recent buildtools (4.1).
=> Fix CI build breakage.

.github/workflows/build-test-deploy.yml, deploy.sh
This deployment process has been tested on my GitHub account using an extra commit to change the destination repo and not push to Docker Hub: https://github.com/pbrkr/yocto-dockerfiles/commit/74021a4badb7d9b447d4a577901da7bc75c54b98
The action results are all good there: https://github.com/pbrkr/yocto-dockerfiles/actions/runs/3928894387
And the containers are visible within my user account: https://github.com/pbrkr/yocto-dockerfiles/pkgs/container/yocto/versions
This *should* work when merged to the main `yocto-dockerfiles` repo but deployments are one of those things that's not possible to perfectly test before merging. Please ping me on IRC before merging this so we can check the results and I can jump in and fix things if there is an issue.
Once this deployment process is confirmed …
=> Deploy to ghcr.io

build_container.sh
When the ENGINE_CMD variable was introduced, the continuation character was missed in two places. Therefore that variable is passed neither in vnc-test.sh, nor in smoke.sh
So in this PR the issue would be fixed.
=> build_container.sh: add missing continuation char
